### ISSUE TITLE
En tant qu'utilisateur, je souhaite sélectionner mon humeur chaque jour de la semaine, afin que mes équipes puissent visualiser

### ISSUE THREAD

**Issue by lahatra3** [iTeam-S/Niko-Niko#3]
## ESTIMATION
5 jours

##  VALEUR
13 points

### Must Have

- lister les groupes
- Poster humeur/jour 
- visualiser humeur

### Should Have

- Modifier humeur

### Could Have 

- Recherche par semaine 

### CRITERES D'ACCEPTATION

- Je peux accéder à mon groupe sans problème.
- Je sais facilement selectionner mon humeur du jour 
- Je peux visualiser les humeurs de mon équipe

**Comment by gaetan1903** [comment]
@lahatra3 tu peux créer ta branche maintenant, j'ai déjà merger l'ancien
